# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/haruhi/ClionProjects/pg_hexretro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/haruhi/ClionProjects/pg_hexretro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/haruhi/ClionProjects/pg_hexretro/CMakeFiles /Users/haruhi/ClionProjects/pg_hexretro//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/haruhi/ClionProjects/pg_hexretro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pg_hexretro

# Build rule for target.
pg_hexretro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pg_hexretro
.PHONY : pg_hexretro

# fast build rule for target.
pg_hexretro/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/build
.PHONY : pg_hexretro/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/main.c.s
.PHONY : main.c.s

pg_access.o: pg_access.c.o
.PHONY : pg_access.o

# target to build an object file
pg_access.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_access.c.o
.PHONY : pg_access.c.o

pg_access.i: pg_access.c.i
.PHONY : pg_access.i

# target to preprocess a source file
pg_access.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_access.c.i
.PHONY : pg_access.c.i

pg_access.s: pg_access.c.s
.PHONY : pg_access.s

# target to generate assembly for a file
pg_access.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_access.c.s
.PHONY : pg_access.c.s

pg_bst.o: pg_bst.c.o
.PHONY : pg_bst.o

# target to build an object file
pg_bst.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_bst.c.o
.PHONY : pg_bst.c.o

pg_bst.i: pg_bst.c.i
.PHONY : pg_bst.i

# target to preprocess a source file
pg_bst.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_bst.c.i
.PHONY : pg_bst.c.i

pg_bst.s: pg_bst.c.s
.PHONY : pg_bst.s

# target to generate assembly for a file
pg_bst.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_bst.c.s
.PHONY : pg_bst.c.s

pg_data.o: pg_data.c.o
.PHONY : pg_data.o

# target to build an object file
pg_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_data.c.o
.PHONY : pg_data.c.o

pg_data.i: pg_data.c.i
.PHONY : pg_data.i

# target to preprocess a source file
pg_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_data.c.i
.PHONY : pg_data.c.i

pg_data.s: pg_data.c.s
.PHONY : pg_data.s

# target to generate assembly for a file
pg_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_data.c.s
.PHONY : pg_data.c.s

pg_default.o: pg_default.c.o
.PHONY : pg_default.o

# target to build an object file
pg_default.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_default.c.o
.PHONY : pg_default.c.o

pg_default.i: pg_default.c.i
.PHONY : pg_default.i

# target to preprocess a source file
pg_default.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_default.c.i
.PHONY : pg_default.c.i

pg_default.s: pg_default.c.s
.PHONY : pg_default.s

# target to generate assembly for a file
pg_default.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_default.c.s
.PHONY : pg_default.c.s

pg_detoast.o: pg_detoast.c.o
.PHONY : pg_detoast.o

# target to build an object file
pg_detoast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_detoast.c.o
.PHONY : pg_detoast.c.o

pg_detoast.i: pg_detoast.c.i
.PHONY : pg_detoast.i

# target to preprocess a source file
pg_detoast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_detoast.c.i
.PHONY : pg_detoast.c.i

pg_detoast.s: pg_detoast.c.s
.PHONY : pg_detoast.s

# target to generate assembly for a file
pg_detoast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_detoast.c.s
.PHONY : pg_detoast.c.s

pg_extra.o: pg_extra.c.o
.PHONY : pg_extra.o

# target to build an object file
pg_extra.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_extra.c.o
.PHONY : pg_extra.c.o

pg_extra.i: pg_extra.c.i
.PHONY : pg_extra.i

# target to preprocess a source file
pg_extra.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_extra.c.i
.PHONY : pg_extra.c.i

pg_extra.s: pg_extra.c.s
.PHONY : pg_extra.s

# target to generate assembly for a file
pg_extra.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_extra.c.s
.PHONY : pg_extra.c.s

pg_integer.o: pg_integer.c.o
.PHONY : pg_integer.o

# target to build an object file
pg_integer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_integer.c.o
.PHONY : pg_integer.c.o

pg_integer.i: pg_integer.c.i
.PHONY : pg_integer.i

# target to preprocess a source file
pg_integer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_integer.c.i
.PHONY : pg_integer.c.i

pg_integer.s: pg_integer.c.s
.PHONY : pg_integer.s

# target to generate assembly for a file
pg_integer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_integer.c.s
.PHONY : pg_integer.c.s

pg_log.o: pg_log.c.o
.PHONY : pg_log.o

# target to build an object file
pg_log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_log.c.o
.PHONY : pg_log.c.o

pg_log.i: pg_log.c.i
.PHONY : pg_log.i

# target to preprocess a source file
pg_log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_log.c.i
.PHONY : pg_log.c.i

pg_log.s: pg_log.c.s
.PHONY : pg_log.s

# target to generate assembly for a file
pg_log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_log.c.s
.PHONY : pg_log.c.s

pg_lzcompress.o: pg_lzcompress.c.o
.PHONY : pg_lzcompress.o

# target to build an object file
pg_lzcompress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_lzcompress.c.o
.PHONY : pg_lzcompress.c.o

pg_lzcompress.i: pg_lzcompress.c.i
.PHONY : pg_lzcompress.i

# target to preprocess a source file
pg_lzcompress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_lzcompress.c.i
.PHONY : pg_lzcompress.c.i

pg_lzcompress.s: pg_lzcompress.c.s
.PHONY : pg_lzcompress.s

# target to generate assembly for a file
pg_lzcompress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_lzcompress.c.s
.PHONY : pg_lzcompress.c.s

pg_output.o: pg_output.c.o
.PHONY : pg_output.o

# target to build an object file
pg_output.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_output.c.o
.PHONY : pg_output.c.o

pg_output.i: pg_output.c.i
.PHONY : pg_output.i

# target to preprocess a source file
pg_output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_output.c.i
.PHONY : pg_output.c.i

pg_output.s: pg_output.c.s
.PHONY : pg_output.s

# target to generate assembly for a file
pg_output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_output.c.s
.PHONY : pg_output.c.s

pg_page.o: pg_page.c.o
.PHONY : pg_page.o

# target to build an object file
pg_page.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_page.c.o
.PHONY : pg_page.c.o

pg_page.i: pg_page.c.i
.PHONY : pg_page.i

# target to preprocess a source file
pg_page.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_page.c.i
.PHONY : pg_page.c.i

pg_page.s: pg_page.c.s
.PHONY : pg_page.s

# target to generate assembly for a file
pg_page.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_page.c.s
.PHONY : pg_page.c.s

pg_relation.o: pg_relation.c.o
.PHONY : pg_relation.o

# target to build an object file
pg_relation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_relation.c.o
.PHONY : pg_relation.c.o

pg_relation.i: pg_relation.c.i
.PHONY : pg_relation.i

# target to preprocess a source file
pg_relation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_relation.c.i
.PHONY : pg_relation.c.i

pg_relation.s: pg_relation.c.s
.PHONY : pg_relation.s

# target to generate assembly for a file
pg_relation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_relation.c.s
.PHONY : pg_relation.c.s

pg_scan.o: pg_scan.c.o
.PHONY : pg_scan.o

# target to build an object file
pg_scan.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_scan.c.o
.PHONY : pg_scan.c.o

pg_scan.i: pg_scan.c.i
.PHONY : pg_scan.i

# target to preprocess a source file
pg_scan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_scan.c.i
.PHONY : pg_scan.c.i

pg_scan.s: pg_scan.c.s
.PHONY : pg_scan.s

# target to generate assembly for a file
pg_scan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_scan.c.s
.PHONY : pg_scan.c.s

pg_shm.o: pg_shm.c.o
.PHONY : pg_shm.o

# target to build an object file
pg_shm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_shm.c.o
.PHONY : pg_shm.c.o

pg_shm.i: pg_shm.c.i
.PHONY : pg_shm.i

# target to preprocess a source file
pg_shm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_shm.c.i
.PHONY : pg_shm.c.i

pg_shm.s: pg_shm.c.s
.PHONY : pg_shm.s

# target to generate assembly for a file
pg_shm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_shm.c.s
.PHONY : pg_shm.c.s

pg_string.o: pg_string.c.o
.PHONY : pg_string.o

# target to build an object file
pg_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_string.c.o
.PHONY : pg_string.c.o

pg_string.i: pg_string.c.i
.PHONY : pg_string.i

# target to preprocess a source file
pg_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_string.c.i
.PHONY : pg_string.c.i

pg_string.s: pg_string.c.s
.PHONY : pg_string.s

# target to generate assembly for a file
pg_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_string.c.s
.PHONY : pg_string.c.s

pg_time.o: pg_time.c.o
.PHONY : pg_time.o

# target to build an object file
pg_time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_time.c.o
.PHONY : pg_time.c.o

pg_time.i: pg_time.c.i
.PHONY : pg_time.i

# target to preprocess a source file
pg_time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_time.c.i
.PHONY : pg_time.c.i

pg_time.s: pg_time.c.s
.PHONY : pg_time.s

# target to generate assembly for a file
pg_time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_time.c.s
.PHONY : pg_time.c.s

pg_toast.o: pg_toast.c.o
.PHONY : pg_toast.o

# target to build an object file
pg_toast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_toast.c.o
.PHONY : pg_toast.c.o

pg_toast.i: pg_toast.c.i
.PHONY : pg_toast.i

# target to preprocess a source file
pg_toast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_toast.c.i
.PHONY : pg_toast.c.i

pg_toast.s: pg_toast.c.s
.PHONY : pg_toast.s

# target to generate assembly for a file
pg_toast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_toast.c.s
.PHONY : pg_toast.c.s

pg_type.o: pg_type.c.o
.PHONY : pg_type.o

# target to build an object file
pg_type.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_type.c.o
.PHONY : pg_type.c.o

pg_type.i: pg_type.c.i
.PHONY : pg_type.i

# target to preprocess a source file
pg_type.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_type.c.i
.PHONY : pg_type.c.i

pg_type.s: pg_type.c.s
.PHONY : pg_type.s

# target to generate assembly for a file
pg_type.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_type.c.s
.PHONY : pg_type.c.s

pg_usage.o: pg_usage.c.o
.PHONY : pg_usage.o

# target to build an object file
pg_usage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_usage.c.o
.PHONY : pg_usage.c.o

pg_usage.i: pg_usage.c.i
.PHONY : pg_usage.i

# target to preprocess a source file
pg_usage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_usage.c.i
.PHONY : pg_usage.c.i

pg_usage.s: pg_usage.c.s
.PHONY : pg_usage.s

# target to generate assembly for a file
pg_usage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_usage.c.s
.PHONY : pg_usage.c.s

pg_varatt.o: pg_varatt.c.o
.PHONY : pg_varatt.o

# target to build an object file
pg_varatt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_varatt.c.o
.PHONY : pg_varatt.c.o

pg_varatt.i: pg_varatt.c.i
.PHONY : pg_varatt.i

# target to preprocess a source file
pg_varatt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_varatt.c.i
.PHONY : pg_varatt.c.i

pg_varatt.s: pg_varatt.c.s
.PHONY : pg_varatt.s

# target to generate assembly for a file
pg_varatt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_varatt.c.s
.PHONY : pg_varatt.c.s

pg_wal.o: pg_wal.c.o
.PHONY : pg_wal.o

# target to build an object file
pg_wal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_wal.c.o
.PHONY : pg_wal.c.o

pg_wal.i: pg_wal.c.i
.PHONY : pg_wal.i

# target to preprocess a source file
pg_wal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_wal.c.i
.PHONY : pg_wal.c.i

pg_wal.s: pg_wal.c.s
.PHONY : pg_wal.s

# target to generate assembly for a file
pg_wal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_wal.c.s
.PHONY : pg_wal.c.s

pg_xact.o: pg_xact.c.o
.PHONY : pg_xact.o

# target to build an object file
pg_xact.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_xact.c.o
.PHONY : pg_xact.c.o

pg_xact.i: pg_xact.c.i
.PHONY : pg_xact.i

# target to preprocess a source file
pg_xact.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_xact.c.i
.PHONY : pg_xact.c.i

pg_xact.s: pg_xact.c.s
.PHONY : pg_xact.s

# target to generate assembly for a file
pg_xact.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pg_hexretro.dir/build.make CMakeFiles/pg_hexretro.dir/pg_xact.c.s
.PHONY : pg_xact.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pg_hexretro"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pg_access.o"
	@echo "... pg_access.i"
	@echo "... pg_access.s"
	@echo "... pg_bst.o"
	@echo "... pg_bst.i"
	@echo "... pg_bst.s"
	@echo "... pg_data.o"
	@echo "... pg_data.i"
	@echo "... pg_data.s"
	@echo "... pg_default.o"
	@echo "... pg_default.i"
	@echo "... pg_default.s"
	@echo "... pg_detoast.o"
	@echo "... pg_detoast.i"
	@echo "... pg_detoast.s"
	@echo "... pg_extra.o"
	@echo "... pg_extra.i"
	@echo "... pg_extra.s"
	@echo "... pg_integer.o"
	@echo "... pg_integer.i"
	@echo "... pg_integer.s"
	@echo "... pg_log.o"
	@echo "... pg_log.i"
	@echo "... pg_log.s"
	@echo "... pg_lzcompress.o"
	@echo "... pg_lzcompress.i"
	@echo "... pg_lzcompress.s"
	@echo "... pg_output.o"
	@echo "... pg_output.i"
	@echo "... pg_output.s"
	@echo "... pg_page.o"
	@echo "... pg_page.i"
	@echo "... pg_page.s"
	@echo "... pg_relation.o"
	@echo "... pg_relation.i"
	@echo "... pg_relation.s"
	@echo "... pg_scan.o"
	@echo "... pg_scan.i"
	@echo "... pg_scan.s"
	@echo "... pg_shm.o"
	@echo "... pg_shm.i"
	@echo "... pg_shm.s"
	@echo "... pg_string.o"
	@echo "... pg_string.i"
	@echo "... pg_string.s"
	@echo "... pg_time.o"
	@echo "... pg_time.i"
	@echo "... pg_time.s"
	@echo "... pg_toast.o"
	@echo "... pg_toast.i"
	@echo "... pg_toast.s"
	@echo "... pg_type.o"
	@echo "... pg_type.i"
	@echo "... pg_type.s"
	@echo "... pg_usage.o"
	@echo "... pg_usage.i"
	@echo "... pg_usage.s"
	@echo "... pg_varatt.o"
	@echo "... pg_varatt.i"
	@echo "... pg_varatt.s"
	@echo "... pg_wal.o"
	@echo "... pg_wal.i"
	@echo "... pg_wal.s"
	@echo "... pg_xact.o"
	@echo "... pg_xact.i"
	@echo "... pg_xact.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

